version: "{branch}.{build}"

environment:
  matrix:
    - TOXENV: py36
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - TOXENV: py37
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

    - TOXENV: py38
      PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

install:
  - pip install tox

build: off

test_script: tox

notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
